apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: nodejs
      labels: # labels to select/identify the deployment
        app: nodejs  
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:     # pod spec                  
      containers:
      - name: nodejs
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: nodejsport
          containerPort: {{ .Values.service.port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          - name: PORT
            value : "{{ .Values.service.port }}"
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
